### ISSUE TITLE
Error calling GoTagAdd json

### ISSUE THREAD

**Issue by Dread-Code** [olexsmir/gopher.nvim#60] opened 2024-03-01 18:23 UTC
I have the following error:

```cmd
E5108: Error executing lua .../.local/share/nvim/lazy/plenary.nvim/lua/plenary/job.lua:107: gomodifytags: Executable not found
stack traceback:
        .../.local/share/nvim/lazy/plenary.nvim/lua/plenary/job.lua:107: in function 'new'
        ...l/share/nvim/lazy/gopher.nvim/lua/gopher/struct_tags.lua:45: in function 'modify'
        ...l/share/nvim/lazy/gopher.nvim/lua/gopher/struct_tags.lua:100: in function 'tags_add'
        [string ":lua"]:1: in main chunk
stack traceback:
        [C]: in function 'error'
        .../.local/share/nvim/lazy/plenary.nvim/lua/plenary/job.lua:107: in function 'new'
        ...l/share/nvim/lazy/gopher.nvim/lua/gopher/struct_tags.lua:45: in function 'modify'
        ...l/share/nvim/lazy/gopher.nvim/lua/gopher/struct_tags.lua:100: in function 'tags_add'
        [string ":lua"]:1: in main chunk
```

**Comment by olexsmir** [comment] 2024-03-01 19:31
Duplicate of #45

**Comment by Dread-Code** [comment] 2024-03-01 22:51
THX!!!

I solved just adding the `~/go/bin` to the `PATH` variable in my `.zshrc`:

```lua
PATH="/path/to/dir1:~/go/bin:$PATH"
```

**Closed** 2024-03-01 23:00 UTC
